runtime: nodejs20

service: client  # This defines the service name for the client app

handlers:
- url: /(.*\..+)$
  static_files: build/\1
  upload: build/(.*\..+)$

- url: /.*
  static_files: build/index.html
  upload: build/index.html